name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
      # In this case, we are using Node.js, so must set it up with a setup-node action.
      - name: use node.js
        uses: actions/setup-node@v3 #ONe of thousands of actions inside github marketplace.
        with: # Since we are using node js, must use this with to specify the version.
          node-version: '18.x'
      - run: npm install # With a build tool, use this to locally build Next.js code
      - run: npm run build
